// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByfHtpMfzFsjhZBbV2Jw8ESkpmghU-w30',
    appId: '1:114331409461:web:71ce2b94b759774a47257c',
    messagingSenderId: '114331409461',
    projectId: 'flutter-crud-d9526',
    authDomain: 'flutter-crud-d9526.firebaseapp.com',
    storageBucket: 'flutter-crud-d9526.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbzWc_aqXBkp_ugk35cHmNRYV3fwe3FWc',
    appId: '1:114331409461:android:8daa91a677b5b37847257c',
    messagingSenderId: '114331409461',
    projectId: 'flutter-crud-d9526',
    storageBucket: 'flutter-crud-d9526.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKuf3yeOPxDicJreE3tm7rFMoERkg2LPc',
    appId: '1:114331409461:ios:aaa4915d3d233dff47257c',
    messagingSenderId: '114331409461',
    projectId: 'flutter-crud-d9526',
    storageBucket: 'flutter-crud-d9526.appspot.com',
    iosClientId: '114331409461-8is403odk1lk6k3g967ngbffsvgqvuq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKuf3yeOPxDicJreE3tm7rFMoERkg2LPc',
    appId: '1:114331409461:ios:aaa4915d3d233dff47257c',
    messagingSenderId: '114331409461',
    projectId: 'flutter-crud-d9526',
    storageBucket: 'flutter-crud-d9526.appspot.com',
    iosClientId: '114331409461-8is403odk1lk6k3g967ngbffsvgqvuq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCrud',
  );
}
